### ISSUE TITLE
What's the reproduced results of the proposed GreaphRec in the paper?

### ISSUE THREAD

**Issue by lcwy220** [Wang-Shuo/GraphRec_PyTorch#7]

**Comment by lcwy220** [comment]
Sorry that I have a misoperation of the title.
I try to reproduce the results with current version, and find that it worse than the claimed results in the paper. Since the authors did not share the whole process in his official version, I'm not sure which one is correct. So do anyone have already reproduced the claimed results in the paper?

**Comment by Wang-Shuo** [comment]
as I claimed in [this issue](https://github.com/Wang-Shuo/GraphRec_PyTorch/issues/2#issuecomment-554756755), I failed to reproduce the results either.

**Comment by lcwy220** [comment]
@Wang-Shuo I found that in the original paper, the Epinions has 18088 users and 261649 items, which is different from the dataset in this repo (49290 users and 139738 items). So the two datasets are different and downloaded from different sources. I think this may be the reason why the model cannot reproduce the results, and I will try it later. Furthermore, the authors were supposed to filter the data and remove some users and items. I haven't processed the Ciao dataset.
Besides, I  want to consult you another question. In the data preprocessing,  the u_items denotes the set of items the user has interacted with. The final predictive goal is to calculate the rating of user and item. However, for each predicted item, it has already included in the u_items to aggregate the user embedding. So does it a kind of advanced exposure，and whether it may impact the model performance?

**Comment by AIRobotZhang** [comment]
> @Wang-Shuo I found that in the original paper, the Epinions has 18088 users and 261649 items, which is different from the dataset in this repo (49290 users and 139738 items). So the two datasets are different and downloaded from different sources. I think this may be the reason why the model cannot reproduce the results, and I will try it later. Furthermore, the authors were supposed to filter the data and remove some users and items. I haven't processed the Ciao dataset.
> Besides, I want to consult you another question. In the data preprocessing, the u_items denotes the set of items the user has interacted with. The final predictive goal is to calculate the rating of user and item. However, for each predicted item, it has already included in the u_items to aggregate the user embedding. So does it a kind of advanced exposure，and whether it may impact the model performance?

I think you should construct the interaction items only depend on train dataset

**Comment by AIRobotZhang** [comment]
> @Wang-Shuo I found that in the original paper, the Epinions has 18088 users and 261649 items, which is different from the dataset in this repo (49290 users and 139738 items). So the two datasets are different and downloaded from different sources. I think this may be the reason why the model cannot reproduce the results, and I will try it later. Furthermore, the authors were supposed to filter the data and remove some users and items. I haven't processed the Ciao dataset.
> Besides, I want to consult you another question. In the data preprocessing, the u_items denotes the set of items the user has interacted with. The final predictive goal is to calculate the rating of user and item. However, for each predicted item, it has already included in the u_items to aggregate the user embedding. So does it a kind of advanced exposure，and whether it may impact the model performance?

I think items interaction should be constructed based on training set.

**Comment by lcwy220** [comment]
> > @Wang-Shuo I found that in the original paper, the Epinions has 18088 users and 261649 items, which is different from the dataset in this repo (49290 users and 139738 items). So the two datasets are different and downloaded from different sources. I think this may be the reason why the model cannot reproduce the results, and I will try it later. Furthermore, the authors were supposed to filter the data and remove some users and items. I haven't processed the Ciao dataset.
> > Besides, I want to consult you another question. In the data preprocessing, the u_items denotes the set of items the user has interacted with. The final predictive goal is to calculate the rating of user and item. However, for each predicted item, it has already included in the u_items to aggregate the user embedding. So does it a kind of advanced exposure，and whether it may impact the model performance?
> 
> I think items interaction should be constructed based on training set.

Yes，you‘re right, and I also have realized it after analyzing the build-data code in detail. Meanwhile, I also noticed that the proposed results in the paper maybe are correct since the results are not good enough compared with those on the other Epinions dataset, at least (mae 0.8168 and rmse 1.0631 in the paper). Maybe the baselines should be finetuned carefully.

**Comment by TZYSJTU** [comment]
I know why you can't reproduce this paper because you have problems with data preprocessing. When you count the number of users and items, you take the maximum id index. In fact, some ids do not have information, which means that your user-item graph is more sparse than the actual one, so it is more difficult to train the network.

**Comment by TZYSJTU** [comment]
My preprocessing has reached the same statistical results as the paper, and effect claimed in the paper has been reproduced. During preprocessing, all users of the user-item graph and all users of the social graph are intersected. Then you can get the actual useful users (7317 users for Ciao) . And only items related to these 7317 users are kept.

**Comment by lcwy220** [comment]
> My preprocessing has reached the same statistical results as the paper, and effect claimed in the paper has been reproduced. During preprocessing, all users of the user-item graph and all users of the social graph are intersected. Then you can get the actual useful users (7317 users for Ciao) . And only items related to these 7317 users are kept.

Thanks. As stated in most papers that they all have filtered out the data to make sure all items must have at least 5 ratings. So, in your statement, you mean that all users must have interacted items and social friends? Since some users have interacted items but their social relationship is none, do these users are also kept?

**Comment by TZYSJTU** [comment]
No



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lcwy220"<notifications@github.com&gt;; 
发送时间: 2020年6月10日(星期三) 上午10:04
收件人: "Wang-Shuo/GraphRec_PyTorch"<GraphRec_PyTorch@noreply.github.com&gt;; 
抄送: "Einsames Brandenburg"<1390139621@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Wang-Shuo/GraphRec_PyTorch] What&#39;s the reproduced results of the proposed GreaphRec in the paper? (#7)





  
My preprocessing has reached the same statistical results as the paper, and effect claimed in the paper has been reproduced. During preprocessing, all users of the user-item graph and all users of the social graph are intersected. Then you can get the actual useful users (7317 users for Ciao) . And only items related to these 7317 users are kept.
  
Thanks. As stated in most papers that they all have filtered out the data to make sure all items must have at least 5 ratings. So, in your statement, you mean that all users must have interacted items and social friends? Since some users have interacted items but their social relationship is none, do these users are also kept?

**Comment by lcwy220** [comment]
> No
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lcwy220"<notifications@github.com&gt;; 发送时间: 2020年6月10日(星期三) 上午10:04 收件人: "Wang-Shuo/GraphRec_PyTorch"<GraphRec_PyTorch@noreply.github.com&gt;; 抄送: "Einsames Brandenburg"<1390139621@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Wang-Shuo/GraphRec_PyTorch] What&#39;s the reproduced results of the proposed GreaphRec in the paper? (#7) My preprocessing has reached the same statistical results as the paper, and effect claimed in the paper has been reproduced. During preprocessing, all users of the user-item graph and all users of the social graph are intersected. Then you can get the actual useful users (7317 users for Ciao) . And only items related to these 7317 users are kept. Thanks. As stated in most papers that they all have filtered out the data to make sure all items must have at least 5 ratings. So, in your statement, you mean that all users must have interacted items and social friends? Since some users have interacted items but their social relationship is none, do these users are also kept? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Oh, I see. According to your description, the results should be able to be reproduced because the data is abundant for each user and item. By the way, would you mind sending me the preprocessing code since I want to carefully rebuild my dataset ? Or could you give me a link where I can find the similar preprocessing code. Thanks!

**Comment by TZYSJTU** [comment]
我整理一下，周末给你



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lcwy220"<notifications@github.com&gt;; 
发送时间: 2020年6月10日(星期三) 上午10:32
收件人: "Wang-Shuo/GraphRec_PyTorch"<GraphRec_PyTorch@noreply.github.com&gt;; 
抄送: "Einsames Brandenburg"<1390139621@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Wang-Shuo/GraphRec_PyTorch] What&#39;s the reproduced results of the proposed GreaphRec in the paper? (#7)





  
No
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lcwy220"<notifications@github.com&gt;; 发送时间: 2020年6月10日(星期三) 上午10:04 收件人: "Wang-Shuo/GraphRec_PyTorch"<GraphRec_PyTorch@noreply.github.com&gt;; 抄送: "Einsames Brandenburg"<1390139621@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Wang-Shuo/GraphRec_PyTorch] What's the reproduced results of the proposed GreaphRec in the paper? (#7) My preprocessing has reached the same statistical results as the paper, and effect claimed in the paper has been reproduced. During preprocessing, all users of the user-item graph and all users of the social graph are intersected. Then you can get the actual useful users (7317 users for Ciao) . And only items related to these 7317 users are kept. Thanks. As stated in most papers that they all have filtered out the data to make sure all items must have at least 5 ratings. So, in your statement, you mean that all users must have interacted items and social friends? Since some users have interacted items but their social relationship is none, do these users are also kept? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
Oh, I see. According to your description, the results should be able to be reproduced because the data is abundant for each user and item. By the way, would you mind sending me the preprocessing code since I want to carefully rebuild my dataset ? Or could you give me a link where I can find the similar preprocessing code. Thanks!

**Comment by lcwy220** [comment]
> 我整理一下，周末给你
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lcwy220"<notifications@github.com&gt;; 发送时间: 2020年6月10日(星期三) 上午10:32 收件人: "Wang-Shuo/GraphRec_PyTorch"<GraphRec_PyTorch@noreply.github.com&gt;; 抄送: "Einsames Brandenburg"<1390139621@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Wang-Shuo/GraphRec_PyTorch] What&#39;s the reproduced results of the proposed GreaphRec in the paper? (#7) No … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lcwy220"<notifications@github.com&gt;; 发送时间: 2020年6月10日(星期三) 上午10:04 收件人: "Wang-Shuo/GraphRec_PyTorch"<GraphRec_PyTorch@noreply.github.com&gt;; 抄送: "Einsames Brandenburg"<1390139621@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Wang-Shuo/GraphRec_PyTorch] What's the reproduced results of the proposed GreaphRec in the paper? (#7) My preprocessing has reached the same statistical results as the paper, and effect claimed in the paper has been reproduced. During preprocessing, all users of the user-item graph and all users of the social graph are intersected. Then you can get the actual useful users (7317 users for Ciao) . And only items related to these 7317 users are kept. Thanks. As stated in most papers that they all have filtered out the data to make sure all items must have at least 5 ratings. So, in your statement, you mean that all users must have interacted items and social friends? Since some users have interacted items but their social relationship is none, do these users are also kept? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Oh, I see. According to your description, the results should be able to be reproduced because the data is abundant for each user and item. By the way, would you mind sending me the preprocessing code since I want to carefully rebuild my dataset ? Or could you give me a link where I can find the similar preprocessing code. Thanks! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Wow, many thanks~

**Comment by aashishkolluri** [comment]
I have been following your conversation. I am also trying to reproduce the results and I have failed to do so. It would be nice if you could share the preprocessing code with which the results can be reproduced. Thanks in advance! @TZYSJTU

**Comment by aashishkolluri** [comment]
> My preprocessing has reached the same statistical results as the paper, and effect claimed in the paper has been reproduced. During preprocessing, all users of the user-item graph and all users of the social graph are intersected. Then you can get the actual useful users (7317 users for Ciao) . And only items related to these 7317 users are kept.

I have taken the intersection of user-item graph and social graph to get the desired users. However, with the given code I do not get the RMSE to 0.9794 as claimed by the paper for Ciao dataset. It is still above 1.09. Did you actually get an RMSE of 0.9794 when you said you were able to reproduce the paper just with preprocessing and not changing the existing code in this repo?

Thanks,
Aashish

**Comment by TZYSJTU** [comment]
Another mistake in Wang-shuo's code is utils.py. 
For each user, all interactive information should be used instead of sampling 30 items.
utils.py needs to be rewritten.

**Comment by aashishkolluri** [comment]
I tried doing that, CUDA runs out of memory now.

**Comment by lcwy220** [comment]
In model.py, if you use different self.aggre_items function to activate the aggregation information, the result may be improved in some how.

**Comment by TZYSJTU** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lcwy220"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月14日(星期天) 上午10:38
收件人:&nbsp;"Wang-Shuo/GraphRec_PyTorch"<GraphRec_PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"Einsames Brandenburg"<1390139621@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Wang-Shuo/GraphRec_PyTorch] What's the reproduced results of the proposed GreaphRec in the paper? (#7)





 
In model.py, if you use different self.aggre_items function to activate the aggregation information, the result may be improved in some how.

**Comment by lcwy220** [comment]
Ok I come again to report my results.
I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.

**Comment by 547577582** [comment]
> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.



> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.



> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.

would you mind sending me the preprocessing code

> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.



> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.



> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.



> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.

I am trying to reproduce the results. Would you mind sending me the preprocessing code. Thanks in advance!

**Comment by 547577582** [comment]
> Ok I come again to report my results.
> I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.

I am failed to reproduce the results. Wound you mind sending me the preprocessing code with which the results can be reproduced. Thanks in advance!

**Comment by lcwy220** [comment]
> > Ok I come again to report my results.
> > I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> > The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.
> 
> I am failed to reproduce the results. Wound you mind sending me the preprocessing code with which the results can be reproduced. Thanks in advance!

Ok， give me your email, and so that you can also check my code.

**Comment by lcwy220** [comment]
> > Ok I come again to report my results.
> > I filtered the Epinions data with each user has at least 5 items, and then I got 23253 users and corresponding 120711 items (not the same size with the paper). When 80% data was used to train the model, and 10% and another 10% were used as validation and testing data, I chose the best performance on the validation set and checked the corresponding performance on the test data.
> > The MAE was 0.814 and RMSE was 1.0643, which nearly were the same with the reported results (0.8168 and 1.0631) in the paper.
> 
> I am failed to reproduce the results. Wound you mind sending me the preprocessing code with which the results can be reproduced. Thanks in advance!

I release the code in my repository (https://github.com/lcwy220/Social-Recommendation/tree/master/Graphrec) with annotating that the codes are modified on this repository. You can check the code, and run it for several times. The result is unstable, so I choose the best in 30 epochs.  
If you find something wrong about the code, please tell me.
